---
title: "modeling"
output: pdf_document
---

``` {r install packages}
#install.packages('GGally')
#install.packages('moments')
#install.packages("corrplot") 

install.packages('GGally', repos='https://ftp.osuosl.org/pub/cran/')
install.packages('moments', repos='https://ftp.osuosl.org/pub/cran/')
install.packages("corrplot", repos = "http://cran.us.r-project.org") 
```

```{r load packages, message = FALSE}
library(GGally)
library(ggplot2) 
library(lmtest)
library(lubridate)
library(moments)
library(sandwich)
library(stargazer)
library(tidyverse)
library(data.table)

source('./functions/get_robust_se.R')
source('./functions/get_clean_dataset.R')
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r data load cleaning}
data_clean <- get_clean_dataset()
glimpse(data_clean)
```

```{r preliminary models}
model_small  <- lm(log_installs ~ 1 + rating, data = data_clean)
model_medium <- lm(log_installs ~ 1 + rating + log_size + log_current_version +
                     log_last_updated + is_free + is_family_category + 
                     is_game_category + is_tools_category + is_content_everyone,
                   data = data_clean)
model_large  <- lm(log_installs ~ 1 + rating + log_size + log_current_version +
                     log_last_updated + is_free + is_content_everyone +
                     rating * is_family_category + rating * is_game_category + 
                     rating * is_tools_category,
                   data = data_clean)

stargazer(
  model_small,
  model_medium,
  model_large,
  type = "text",
  se = list(get_robust_se(model_small), get_robust_se(model_medium), 
            get_robust_se(model_large))
)

plot(model_small)
plot(model_medium)
plot(model_large)
```

```{r qq plot}
plot(model_large)
```

